/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0037b0',
        'primary-container': '#1d4ed8',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#cad3ff',
        'on-primary-fixed': '#001551',
        'on-primary-fixed-variant': '#0039b5',
        'inverse-primary': '#b7c4ff',

        secondary: '#9a4600',
        'secondary-container': '#fe852f',
        'secondary-fixed': '#ffdbc9',
        'secondary-fixed-dim': '#ffb68c',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#642b00',
        'on-secondary-fixed': '#321200',
        'on-secondary-fixed-variant': '#753400',

        tertiary: '#004f27',
        'tertiary-container': '#006a36',
        'tertiary-fixed': '#90f8ad',
        'tertiary-fixed-dim': '#74db92',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#82ea9f',
        'on-tertiary-fixed': '#00210d',
        'on-tertiary-fixed-variant': '#005228',

        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        background: '#faf9ff',
        'on-background': '#0f1b33',

        surface: '#faf9ff',
        'on-surface': '#0f1b33',
        'on-surface-variant': '#434655',
        'surface-tint': '#2151da',
        'surface-dim': '#cedafa',
        'surface-bright': '#faf9ff',
        'surface-variant': '#d8e2ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e1e8ff',
        'surface-container-highest': '#d8e2ff',

        'inverse-surface': '#253049',
        'inverse-on-surface': '#edf0ff',

        outline: '#747686',
        'outline-variant': '#c4c5d7',

        // Verdict Tokens
        verdict: {
          verified: {
            DEFAULT: '#1E8E4E',
            bg: '#EAF6EE',
            border: '#B8E4C8',
            text: '#146336',
          },
          false: {
            DEFAULT: '#C62F2F',
            bg: '#FDF2F2',
            border: '#F6B8B8',
            text: '#991B1B',
          },
          outdated: {
            DEFAULT: '#D9730D',
            bg: '#FEF7ED',
            border: '#FCD4A5',
            text: '#A04F05',
          },
          partly: {
            DEFAULT: '#B7950B',
            bg: '#FEFCE8',
            border: '#FBE89B',
            text: '#856807',
          },
          unconfirmed: {
            DEFAULT: '#64748B',
            bg: '#F1F5F9',
            border: '#CBD5E1',
            text: '#475569',
          },
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        gutter: '1rem',
        'gutter-desktop': '1.5rem',
        margin: '1rem',
        'margin-tablet': '1.5rem',
        'margin-desktop': '2rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        serif: ['"Source Serif 4"', 'serif'],
        mono: ['"Space Mono"', 'monospace'],
        devanagari: ['"Noto Sans Devanagari"', 'sans-serif'],
        'quoted-claim': ['"Source Serif 4"', 'serif'],
        'quoted-claim-lg': ['"Source Serif 4"', 'serif'],
        'code-sm': ['"Space Mono"', 'monospace'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'code-sm': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg-mobile': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'quoted-claim': ['16px', { lineHeight: '26px', letterSpacing: '0', fontWeight: '400' }],
        'quoted-claim-lg': ['19px', { lineHeight: '30px', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
